DROP TABLE IF EXISTS zoro;
CREATE TABLE zoro(ID INT, NAME VARCHAR(50), PASSWORD VARCHAR(50));

DROP TABLE IF EXISTS authorities;
CREATE TABLE authorities(ID INT, NAME VARCHAR(50), authority VARCHAR(50));
